Feat/close instruments
instrumentkit/InstrumentKit pull request #376
Opened 2022-10-07 20:32 UTC by Gracecr

Allows for instruments to be used as context managers so you can do things like:

```python
with ik.Instrument.open_test() as instr:
        instr.do_something()
```

This way you can be confident your connection is being closed properly.

2022-10-13 16:41 UTC, Gracecr commented
Sort of addresses #215. I can add an actual `close` method to `Instrument` if desired.

2022-10-21 13:30 UTC, scasagrande commented
Sorry for the delay

Looks reasonable to me

I need to fix CI but then I'll get your PR merged in: #374

2022-11-01 21:01 UTC, scasagrande requested changes
please update branch to bring in the other fixes

just 1 change requested

2022-11-03 21:31 UTC, Gracecr commented on tests/test_base_instrument.py
> +from instruments.abstract_instruments import instrument
Shouldn't have these import there in the first place. Good catch.

2022-11-03 22:32 UTC, scasagrande approved these changes
lgtm! thank you for your contribution

2022-11-03 22:32 UTC, merged